### ISSUE TITLE
hover issue on prior year workshop links

### ISSUE THREAD

**Issue by dzoladz** [code4lib/2021.code4lib.org#45]
Hovering over any link for a prior year's workshops darkens the links

See: `http://127.0.0.1:4000/general-info/propose-a-workshop.html`

![hover_issue](https://user-images.githubusercontent.com/10561752/100021117-f8ffb880-2dae-11eb-8e08-823a9ecd6582.gif)

**Comment by jscaffrey** [comment]
The bug is because there is no class assigned on these subpage templates, so it's calling CSS rules for `a` only. I can't find where `a` without classes are specified in our SCSS assets, so I'm seeking help on this issue. 

It would be relatively easier, but less technically elegant to just assign it a class and specify what colors should be. If you prefer I go that route, I can do it on my own.

**Comment by dzoladz** [comment]
I'll take a look this evening
